sites:
  - name: "Central Site"
    controlChannel: "772.74375"
    voiceChannels:
      - "771.66875"
      - "772.46875"
      - "773.74375"
      - "855.7375"
    location:
      X: 757.89
      Y: 1274.17
      Z: 360.3
    systemID: 1
    siteID: 1
    range: 1.5

  - name: "Central-West Site"
    controlChannel: "852.8875"
    voiceChannels:
      - "857.2625"
      - "857.4375"
      - "851.7375"
    location:
      X: -2312.05
      Y: 336.79
      Z: 188.6
    systemID: 1
    siteID: 2
    range: 1.5

  - name: "City-FBI Site"
    controlChannel: "773.66875"
    voiceChannels:
      - "774.89375"
      - "772.11875"
      - "771.06875"
      - "770.04375"
      - "769.28125"
    location:
      X: 148.69
      Y: -770.36
      Z: 262.85
    systemID: 1
    siteID: 3
    range: 2.0

  - name: "North-East Site"
    controlChannel: "854.9625"
    voiceChannels:
      - "853.2125"
      - "852.6625"
      - "852.0375"
      - "851.7125"
      - "773.16875"
      - "769.36875"
    location:
      X: 1869.07
      Y: 3715.00
      Z: 33.06
    systemID: 1
    siteID: 4
    range: 1.5

  - name: "North-Central Site"
    controlChannel: "856.7625"
    voiceChannels:
      - "855.4625"
      - "855.2125"
      - "852.9125"
      - "852.0625"
    location:
      X: 450.82
      Y: 5567.40
      Z: 796.62
    systemID: 1
    siteID: 5
    range: 2.0

    ###
    # Uncomment the following if your FiveM server has Roxwood
    ###

  - name: "Roxwood West Site"
    controlChannel: "854.5125"
    voiceChannels:
        - "853.8625"
        - "853.3125"
        - "852.6125"
    location:
        X: -1707.05
        Y: 6824.27
        Z: 94.5
    systemID: 2
    siteID: 7
    range: 1.0